// Entrypoint. Boots the HTTP server, runs lightweight startup probes, and wires
// graceful shutdown so in-flight requests drain and connections close cleanly.
import { serve } from '@hono/node-server';
import { buildApp } from './app.js';
import { env } from './env.js';
import { log } from './logger.js';
import { pingRedis, closeRedis } from './store.js';
import { pingDb, closeDb } from './db.js';
import { ensureVectorIndex } from './vector.js';
import { startFileWorkers, stopFileWorkers } from './files/worker.js';
import { hashKey } from './apikeys.js';
import { SCHEMA, tryQuery, query } from './db.js';
import { autoGeneratedSecrets, secretsFilePath } from './secrets.js';
import { spawn, type ChildProcess } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

/** Apply db/schema.sql on boot (idempotent) — replaces the standalone migrate
 * container. Safe to run every start; DDL uses IF NOT EXISTS. */
async function runStartupMigration(): Promise<boolean> {
  // Wait for the DB (a full-stack cold start races the datastores), then apply the
  // schema. Returns whether the DB is usable. Idempotent (DDL uses IF NOT EXISTS).
  let up = false;
  for (let i = 0; i < 20; i++) {
    if (await pingDb()) { up = true; break; }
    if (i === 0) log.info('waiting for database…');
    await new Promise((r) => setTimeout(r, 3000));
  }
  if (!up) { log.warn('database not reachable after ~60s — running degraded (no persistence)'); return false; }
  const candidates = [resolve(HERE, '..', 'db', 'schema.sql'), resolve(HERE, '..', '..', 'db', 'schema.sql')];
  const p = candidates.find((c) => existsSync(c));
  if (!p) { log.warn('schema.sql not found — skipping startup migration', { tried: candidates }); return true; }
  try {
    await query(readFileSync(p, 'utf8'));
    log.info('startup migration applied', { schema: p });
  } catch (e) {
    log.error('startup migration failed', { error: (e as Error).message });
  }
  return true;
}

/** Start the MCP server (Streamable HTTP) as a child of the API process, so a
 * single container serves both. Disable with HDSEARCH_MCP_ENABLED=false. */
let mcpChild: ChildProcess | undefined;
function startMcpChild(): void {
  if (/^(0|false|no|off)$/i.test(process.env.HDSEARCH_MCP_ENABLED || '')) return;
  const script = resolve(HERE, '..', 'mcp', 'server.js');
  if (!existsSync(script)) { log.warn('mcp server.js not found — skipping', { script }); return; }
  const port = process.env.MCP_PORT || '8792';
  mcpChild = spawn(process.execPath, [script, '--http'], {
    env: { ...process.env, HDSEARCH_API_URL: `http://127.0.0.1:${env.port}`, MCP_PORT: String(port) },
    stdio: 'inherit',
  });
  mcpChild.on('exit', (code) => { if (code) log.warn('mcp child exited', { code }); });
  log.info('mcp (streamable-http) started in-container', { port });
}

async function bootstrapAdminKey(): Promise<void> {
  if (!env.bootstrapAdminKey) return;
  if (!env.bootstrapAdminKey.startsWith('sk-hds-')) {
    log.warn('HDSEARCH_API_BOOTSTRAP_ADMIN_KEY must start with sk-hds-; skipping');
    return;
  }
  // only if no keys exist yet
  const existing = await tryQuery<{ n: string }>(`select count(*)::text as n from ${SCHEMA}.api_keys`);
  if (existing[0] && Number(existing[0].n) > 0) return;
  // ensure a bootstrap user exists, then insert the provided key directly
  await tryQuery(
    `insert into ${SCHEMA}.users (id, plan) values ('bootstrap-admin','enterprise') on conflict (id) do nothing`,
  );
  await tryQuery(
    `insert into ${SCHEMA}.api_keys (id, user_id, name, key_hash, key_prefix, scopes, rate_limit_per_min, status)
     values ('key_bootstrap','bootstrap-admin','bootstrap', $1, $2, ARRAY['search:read','crawl:read','vector:read','admin:keys'], 1000, 'active')
     on conflict (key_hash) do nothing`,
    [hashKey(env.bootstrapAdminKey), env.bootstrapAdminKey.slice(0, 12)],
  );
  log.info('bootstrap admin API key installed');
}

/** Create the local admin account from HDSEARCH_ADMIN_EMAIL/PASSWORD on first run
 * (headless/Docker bootstrap). No-op once any local account exists. */
async function bootstrapAdminUser(): Promise<void> {
  if (!env.adminEmail || !env.adminPassword) return;
  const { isSetupRequired, localUserId } = await import('./routes/auth-local.js');
  if (!(await isSetupRequired())) return;
  const { hashPassword, validatePassword } = await import('./password.js');
  const pwErr = validatePassword(env.adminPassword);
  if (pwErr) {
    log.warn('HDSEARCH_ADMIN_PASSWORD rejected; skipping admin bootstrap', { reason: pwErr });
    return;
  }
  const id = localUserId(env.adminEmail);
  await tryQuery(
    `insert into ${SCHEMA}.users (id, email, name, plan, role, password_hash, updated_at)
       values ($1,$2,$3,'free','admin',$4, now())
     on conflict (id) do update set role='admin', password_hash=excluded.password_hash, updated_at=now()`,
    [id, env.adminEmail, env.adminEmail.split('@')[0], hashPassword(env.adminPassword)],
  );
  log.info('bootstrapped local admin account from env', { email: env.adminEmail });
}

async function main() {
  log.info('hd-search starting', { runMode: env.runMode, port: env.port, embeddings: env.embeddingsProvider });

  // transparency: note any secrets that were auto-generated this boot
  const gen = autoGeneratedSecrets();
  if (gen.length) {
    log.warn('auto-generated secrets persisted (set these in production + back up the file)', {
      generated: gen,
      file: secretsFilePath(),
    });
  }

  // best-effort startup probes (don't block boot on optional deps)
  const redisOk = await pingRedis();
  if (!redisOk) log.warn('redis not reachable at boot — cache/keys degraded until it returns');
  const dbOk = await runStartupMigration(); // waits for DB, applies schema, returns readiness
  if (dbOk) await bootstrapAdminKey().catch((e) => log.warn('bootstrap admin failed', { error: (e as Error).message }));
  if (dbOk) await bootstrapAdminUser().catch((e) => log.warn('bootstrap admin user failed', { error: (e as Error).message }));
  ensureVectorIndex().catch(() => {});

  // File-processing workers (upload → parse → embed → index). Resilient to Redis/DB
  // outages; reconciles anything a prior crash left mid-flight. Safe when idle.
  startFileWorkers();

  // Load LLM models from DB (sync JSON defaults on first run)
  if (dbOk) {
    const { refreshFromDb } = await import('./ai/models.js');
    await refreshFromDb().catch((e) => log.warn('LLM registry DB sync failed (using JSON fallback)', { error: (e as Error).message }));
  }

  const app = buildApp();
  const server = serve({ fetch: app.fetch, port: env.port, hostname: env.host }, (info) => {
    log.info('hd-search listening', { addr: `http://${env.host}:${info.port}` });
    startMcpChild(); // MCP Streamable HTTP, in the same container (default :8792)
  });

  const shutdown = async (sig: string) => {
    log.info('shutting down', { sig });
    mcpChild?.kill('SIGTERM');
    server.close();
    await stopFileWorkers();
    await Promise.allSettled([closeRedis(), closeDb()]);
    process.exit(0);
  };
  process.on('SIGTERM', () => void shutdown('SIGTERM'));
  process.on('SIGINT', () => void shutdown('SIGINT'));
  process.on('unhandledRejection', (e) => log.error('unhandledRejection', { error: String(e) }));
  process.on('uncaughtException', (e) => log.error('uncaughtException', { error: (e as Error).message, stack: (e as Error).stack }));
}

main().catch((e) => {
  log.error('fatal boot error', { error: (e as Error).message, stack: (e as Error).stack });
  process.exit(1);
});
