// Auto-provisioned secrets so HD-Search "just works" when run directly (without the
// start scripts that normally generate/sync them). For each secret, precedence is:
//   1. the explicit environment variable (always wins — set these in production)
//   2. a value persisted in a shared secrets file (so API + web agree, and values
//      survive restarts — important for HDSEARCH_ENCRYPTION_KEY)
//   3. a freshly generated value, which is then persisted to the file
//
// The file is shared between the API and the web app (same path at the service
// root) so the internal BFF secret matches automatically. Override the location
// with HDSEARCH_SECRETS_FILE (e.g. a mounted volume in Docker).
//
// NOTE: standalone module (no imports from env.ts) to avoid a circular import.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';

const HERE = dirname(fileURLToPath(import.meta.url));

// Find the package root (dir with package.json), then the service root is its parent
// (services/hd-search/), where the shared secrets file lives.
function pkgRoot(): string {
  let dir = HERE;
  for (let i = 0; i < 6; i++) {
    if (existsSync(join(dir, 'package.json'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return resolve(HERE, '..');
}

const SECRETS_FILE =
  process.env.HDSEARCH_SECRETS_FILE || resolve(pkgRoot(), '..', '.hdsearch-secrets.json');

type SecretStore = Record<string, string>;
let cache: SecretStore | null = null;
const generated: string[] = [];

function load(): SecretStore {
  if (cache) return cache;
  try {
    cache = existsSync(SECRETS_FILE) ? (JSON.parse(readFileSync(SECRETS_FILE, 'utf8')) as SecretStore) : {};
  } catch {
    cache = {};
  }
  return cache;
}

function persist(store: SecretStore): void {
  try {
    mkdirSync(dirname(SECRETS_FILE), { recursive: true });
    writeFileSync(SECRETS_FILE, JSON.stringify(store, null, 2), { mode: 0o600 });
  } catch {
    /* read-only fs (e.g. container) — value still returned in-memory for this run */
  }
}

/** Resolve a secret: env → file → generate+persist. `envVal` is the already-read
 *  process.env value (or empty). `bytes` controls generated length (hex). */
export function resolveSecret(key: string, envVal: string | undefined, bytes = 32): string {
  if (envVal && envVal.trim()) return envVal.trim();
  const store = load();
  if (store[key]) return store[key]!;
  const value = randomBytes(bytes).toString('hex');
  store[key] = value;
  persist(store);
  generated.push(key);
  return value;
}

/** Names of secrets that were auto-generated this process (for a startup log). */
export function autoGeneratedSecrets(): string[] {
  return [...generated];
}

export function secretsFilePath(): string {
  return SECRETS_FILE;
}
